name: CookieCore
version: '${project.version}'
main: me.soyaldo.cookiecore.CookieCore
api-version: '1.16'
softdepend: [ PlaceholderAPI ]
authors: [ SoyAldo ]
description: '${project.description}'
website: '${project.url}'

commands:
  cookiecore:
    description: "Admin command for CookieCore."
  actionapi:
    description: "ActionAPI command for test."
  nbtitemapi:
    description: "NBTItemAPI command for test."

permissions:
  cookiecore.admin:
    description: "Access to execute /cookiecore command."
    default: "op"
  cookiecore.actionapi:
    description: "Access s to execute /actionapi command."
    default: "op"
  cookiecore.nbtitemapi:
    description: "Access s to execute /actionapi command."
    default: "op"